version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - progres:/var/lib/postgresql/data
    env_file:
      - ./.env
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  progres:

